version: '3'

networks: { elastic_network_stack: {} }

services:
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    ports: ['9200:9200']
    networks: ['elastic_network_stack']
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: kibana
    ports: ['5601:5601']
    networks: ['elastic_network_stack']
    depends_on: ['elasticsearch']

  logstash:
    build: ./logstash
    container_name: logstash
    networks: ['elastic_network_stack']
    ports: ['5000:5000']
    depends_on: ['elasticsearch']

  # nginx:
  #   image: nginx:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./nginx/config:/etc/nginx/conf.d:ro,Z
  #     - ./nginx/htpasswd.users:/etc/nginx/htpasswd.users:ro,Z
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - kibana

volumes:
  es_data: